### ISSUE TITLE
Segmentation Fault with ifort version 16.0.1

### ISSUE THREAD

**Issue by JannickWeisshaupt** [exciting/exciting#4]
When I compile exciting with ifort version 16.0.1 the program crashes on runtime for larger systems and or high Z atoms with segmentation fault. 

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
excitingser        0000000000D16355  Unknown               Unknown  Unknown
excitingser        0000000000D14117  Unknown               Unknown  Unknown
excitingser        0000000000CA7794  Unknown               Unknown  Unknown
excitingser        0000000000CA75A6  Unknown               Unknown  Unknown
excitingser        0000000000C28719  Unknown               Unknown  Unknown
excitingser        0000000000C2EE40  Unknown               Unknown  Unknown
libpthread.so.0    00007F48A826B100  Unknown               Unknown  Unknown
excitingser        0000000000487D5E  Unknown               Unknown  Unknown
excitingser        00000000004207F9  Unknown               Unknown  Unknown
excitingser        000000000063A331  Unknown               Unknown  Unknown
excitingser        00000000009E1A1B  Unknown               Unknown  Unknown
excitingser        0000000000779172  Unknown               Unknown  Unknown
excitingser        000000000098E7FC  Unknown               Unknown  Unknown
excitingser        0000000000405A5E  Unknown               Unknown  Unknown
libc.so.6          00007F48A7EBCB15  Unknown               Unknown  Unknown
excitingser        000000000040596D  Unknown               Unknown  Unknown

Smaller systems with low Z atoms work fine, e.g. Diamond, Si...
I tried to add -heap-arrays to the compiler flags but then the compilation fails with a seg fault as well. With gfortran the executable runs fine but uses only one core.

**Comment by JannickWeisshaupt** [comment]
I found a way to compile it so that it works but it is extremely ugly.
You have to add -heap-arrays to the compiler flags.
Then compile until the compilation crashes with a seg fault.
Remove the -heap-arrays compiler flag.
Resume compilation and let only the f90 file compile that caused the crash. Then abort compilation.
Add the -heap-arrays flag again and resume compilation.
Repeat roughly 10 times.

**Comment by AlexBuccheri** [comment]
Closing this issue because it's 4 years out of date. In the future, please compile in debug mode to get a proper stack trace and provide relevant inputs.
